name: CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          ref: "master"
      - name: Run linters and tests
        run: chmod +x test.sh && ./test.sh
