name: Release

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          ref: "master"
      - name: Run linters and tests
        run: chmod +x test.sh && ./test.sh
      - name: Upload coverage report
        uses: codecov/codecov-action@v1

  prepare-release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@main
        with:
          ref: "master"
          fetch-depth: "0"
      - name: Prepare release
        env:
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        run: chmod +x prepare-release.sh && ./prepare-release.sh

  release:
    runs-on: ubuntu-latest
    needs: prepare-release
    steps:
      - uses: actions/checkout@main
        with:
          ref: "master"
      - name: Release to Production environment
        env:
          HEROKU_TOKEN: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.HEROKU_ANIME_SUUPU_PROD_APP_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        run: chmod +x release.sh && ./release.sh
